name: Build & Deploy
on:
    workflow_dispatch: 
    schedule:
        - cron: "0 0 * * *"
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build and publish image
              uses: ilteoood/docker_buildx@master
              with:
                publish: true
                imageName: terafin/nodejs-poolcontroller
                dockerFile: nodejs-poolcontroller/Dockerfile
                dockerUser: ${{ secrets.DOCKER_USERNAME }}
                dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
