name: Build & Deploy
on:
    workflow_dispatch: 
    schedule:
        - cron: "0 0 * * *"
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Build and publish image
              uses: ilteoood/docker_buildx@master
              with:
                publish: true
                imageName: nodejs-poolcontroller
                dockerUser: ${{ secrets.DOCKER_USERNAME }}
                dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
#             - name: Build multi platform
#               uses: dawidd6/action-docker-publish-changed@v3
#               with:
#                   username: ${{ secrets.DOCKER_USERNAME }}
#                   password: ${{ secrets.DOCKER_PASSWORD }}
#                   imageName: terafin/
#                   publish: true
#                   platforms: linux/amd64,linux/arm64,linux/arm/v7
#                   tag: latest
