name: Build & Deploy
on:
    workflow_dispatch: 
    schedule:
        - cron: "0 0 * * *"
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Build and publish image
              uses: ilteoood/docker_buildx@master
              with:
                publish: true
                imageName: nodejs-poolcontroller
                dockerFile: nodejs-poolcontroller/Dockerfile
                dockerUser: ${{ secrets.DOCKER_USERNAME }}
                dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
                dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
                dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}
